name: Release
on:
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release:
    uses: joshunrau/semantic-release-config/.github/workflows/release.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
